### ISSUE TITLE
Different technologies

### ISSUE THREAD

**Issue by yasintz** [oguzhaninan/passwall-desktop#7]
The website uses a reactjs and desktop uses vue. It becomes difficult to manage this in the future. I think it should use reactjs on both sides.

**Comment by cyberst** [comment]
+1 
Also, the browser extension uses Vue as well. These can be standardized for better manageability .

**Comment by yakuter** [comment]
Allright, I think the same way. Then let's talk about technologies. I need a tech for both web, extension, desktop (mac, win, linux)

What should we use?

**Comment by cyberst** [comment]
Although that I am really not that experienced on these platforms, as I see them React and Vue both are capable for web, extension and multi OS desktop development with Electron. Maybe the creators of passwall-web, passwall-extension and passwall-desktop projects can simply state why did they choose the current technologies and the discussion can continue from there.

**Comment by hadermendez** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
sunng87, @MichaIJarosz, @pjockey, @Foxsky28, @zihoo, @yasuharu519, @Puri12, @Lucroz94, @vj4a, @kil0rome0, @axifive, @Chamane, @athphane, @mrmorethanu, @zssvaidar, @magnus-cedulas, @zaherg, @hjoway, @a2k42, @Souldiv, @diminou91, @josefhs11, @flfcampos, @dnsergeev, @lordvins226, @hsomesun, @jianan1104, @lcs-felix, @asenov, @kajansasi, @leelianjason, @wkhayrattee, @SiroDiaz, @22mahmoud, @muzaparoff, @amoklilli, @904243852, @Bokonon366, @mozulamt, @mkoch66, @HolyFredy, @kuldeepat1lint, @caryxiao, @nulconaux, @ajq2679, @AmirZaidi65, @Valpluto, @FlaMaaSSteR, @rkrdo, @dapetoo
